
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.csvDeliveryFish
{

public sealed class TbDeliveryFish
{
    private readonly Dictionary<int, csvDeliveryFish.DeliveryFish> _dataMap;
    private readonly List<csvDeliveryFish.DeliveryFish> _dataList;
    
    public TbDeliveryFish(JSONNode _json)
    {
        _dataMap = new Dictionary<int, csvDeliveryFish.DeliveryFish>();
        _dataList = new List<csvDeliveryFish.DeliveryFish>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = csvDeliveryFish.DeliveryFish.DeserializeDeliveryFish(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public Dictionary<int, csvDeliveryFish.DeliveryFish> DataMap => _dataMap;
    public List<csvDeliveryFish.DeliveryFish> DataList => _dataList;

    public csvDeliveryFish.DeliveryFish GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public csvDeliveryFish.DeliveryFish Get(int key) => _dataMap[key];
    public csvDeliveryFish.DeliveryFish this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
}

}