
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.csvPlayerProp
{

public sealed class PlayerProp :  Bright.Config.BeanBase 
{
    public PlayerProp(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["player_speed_mul"].IsNumber) { throw new SerializationException(); }  PlayerSpeedMul = _json["player_speed_mul"]; }
        { if(!_json["dash_cd"].IsNumber) { throw new SerializationException(); }  DashCd = _json["dash_cd"]; }
        { if(!_json["reborn_time"].IsNumber) { throw new SerializationException(); }  RebornTime = _json["reborn_time"]; }
        { if(!_json["reborn_protect"].IsNumber) { throw new SerializationException(); }  RebornProtect = _json["reborn_protect"]; }
        { if(!_json["player_vol_mul"].IsNumber) { throw new SerializationException(); }  PlayerVolMul = _json["player_vol_mul"]; }
        { if(!_json["player_hitback_mul"].IsNumber) { throw new SerializationException(); }  PlayerHitbackMul = _json["player_hitback_mul"]; }
    }

    public PlayerProp(int id, float player_speed_mul, float dash_cd, float reborn_time, float reborn_protect, float player_vol_mul, float player_hitback_mul ) 
    {
        this.Id = id;
        this.PlayerSpeedMul = player_speed_mul;
        this.DashCd = dash_cd;
        this.RebornTime = reborn_time;
        this.RebornProtect = reborn_protect;
        this.PlayerVolMul = player_vol_mul;
        this.PlayerHitbackMul = player_hitback_mul;
    }

    public static PlayerProp DeserializePlayerProp(JSONNode _json)
    {
        return new csvPlayerProp.PlayerProp(_json);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 玩家速度倍数
    /// </summary>
    public float PlayerSpeedMul { get; private set; }
    /// <summary>
    /// 冲撞CD（秒）
    /// </summary>
    public float DashCd { get; private set; }
    /// <summary>
    /// 玩家重生时间（秒）
    /// </summary>
    public float RebornTime { get; private set; }
    /// <summary>
    /// 玩家保护时间（秒）
    /// </summary>
    public float RebornProtect { get; private set; }
    /// <summary>
    /// 玩家体积倍数
    /// </summary>
    public float PlayerVolMul { get; private set; }
    /// <summary>
    /// 击退的距离？
    /// </summary>
    public float PlayerHitbackMul { get; private set; }

    public const int __ID__ = -1245244952;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "PlayerSpeedMul:" + PlayerSpeedMul + ","
        + "DashCd:" + DashCd + ","
        + "RebornTime:" + RebornTime + ","
        + "RebornProtect:" + RebornProtect + ","
        + "PlayerVolMul:" + PlayerVolMul + ","
        + "PlayerHitbackMul:" + PlayerHitbackMul + ","
        + "}";
    }
    }
}
