
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.csvPlayerProp
{

public sealed class TbPlayerProp
{
    private readonly Dictionary<int, csvPlayerProp.PlayerProp> _dataMap;
    private readonly List<csvPlayerProp.PlayerProp> _dataList;
    
    public TbPlayerProp(JSONNode _json)
    {
        _dataMap = new Dictionary<int, csvPlayerProp.PlayerProp>();
        _dataList = new List<csvPlayerProp.PlayerProp>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = csvPlayerProp.PlayerProp.DeserializePlayerProp(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public Dictionary<int, csvPlayerProp.PlayerProp> DataMap => _dataMap;
    public List<csvPlayerProp.PlayerProp> DataList => _dataList;

    public csvPlayerProp.PlayerProp GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public csvPlayerProp.PlayerProp Get(int key) => _dataMap[key];
    public csvPlayerProp.PlayerProp this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
}

}