
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.csvFish
{

public sealed class Fish :  Bright.Config.BeanBase 
{
    public Fish(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["fish_name"].IsString) { throw new SerializationException(); }  FishName = _json["fish_name"]; }
        { if(!_json["fish_name_cn"].IsString) { throw new SerializationException(); }  FishNameCn = _json["fish_name_cn"]; }
        { if(!_json["fish_rarity"].IsNumber) { throw new SerializationException(); }  FishRarity = _json["fish_rarity"]; }
        { if(!_json["fish_point"].IsNumber) { throw new SerializationException(); }  FishPoint = _json["fish_point"]; }
        { if(!_json["fish_weight"].IsNumber) { throw new SerializationException(); }  FishWeight = _json["fish_weight"]; }
        { if(!_json["fish_size_mul"].IsNumber) { throw new SerializationException(); }  FishSizeMul = _json["fish_size_mul"]; }
    }

    public Fish(int id, string fish_name, string fish_name_cn, int fish_rarity, int fish_point, int fish_weight, float fish_size_mul ) 
    {
        this.Id = id;
        this.FishName = fish_name;
        this.FishNameCn = fish_name_cn;
        this.FishRarity = fish_rarity;
        this.FishPoint = fish_point;
        this.FishWeight = fish_weight;
        this.FishSizeMul = fish_size_mul;
    }

    public static Fish DeserializeFish(JSONNode _json)
    {
        return new csvFish.Fish(_json);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 鱼类名称（英文）
    /// </summary>
    public string FishName { get; private set; }
    /// <summary>
    /// 名称注释（中文）
    /// </summary>
    public string FishNameCn { get; private set; }
    /// <summary>
    /// 鱼类稀有度<br/>1= 普通<br/>2= 稀有<br/>3= 非常稀有
    /// </summary>
    public int FishRarity { get; private set; }
    /// <summary>
    /// 鱼类分数
    /// </summary>
    public int FishPoint { get; private set; }
    /// <summary>
    /// 鱼类权重
    /// </summary>
    public int FishWeight { get; private set; }
    /// <summary>
    /// 鱼类体积倍数
    /// </summary>
    public float FishSizeMul { get; private set; }

    public const int __ID__ = 334063848;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "FishName:" + FishName + ","
        + "FishNameCn:" + FishNameCn + ","
        + "FishRarity:" + FishRarity + ","
        + "FishPoint:" + FishPoint + ","
        + "FishWeight:" + FishWeight + ","
        + "FishSizeMul:" + FishSizeMul + ","
        + "}";
    }
    }
}
