
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.csvFish
{

public sealed class TbFish
{
    private readonly Dictionary<int, csvFish.Fish> _dataMap;
    private readonly List<csvFish.Fish> _dataList;
    
    public TbFish(JSONNode _json)
    {
        _dataMap = new Dictionary<int, csvFish.Fish>();
        _dataList = new List<csvFish.Fish>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = csvFish.Fish.DeserializeFish(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public Dictionary<int, csvFish.Fish> DataMap => _dataMap;
    public List<csvFish.Fish> DataList => _dataList;

    public csvFish.Fish GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public csvFish.Fish Get(int key) => _dataMap[key];
    public csvFish.Fish this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
}

}