
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.csvItem
{

public sealed class TbItem
{
    private readonly Dictionary<int, csvItem.Item> _dataMap;
    private readonly List<csvItem.Item> _dataList;
    
    public TbItem(JSONNode _json)
    {
        _dataMap = new Dictionary<int, csvItem.Item>();
        _dataList = new List<csvItem.Item>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = csvItem.Item.DeserializeItem(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public Dictionary<int, csvItem.Item> DataMap => _dataMap;
    public List<csvItem.Item> DataList => _dataList;

    public csvItem.Item GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public csvItem.Item Get(int key) => _dataMap[key];
    public csvItem.Item this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
}

}