
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.csvCommon
{

public sealed class TbCommon
{
    private readonly Dictionary<int, csvCommon.Common> _dataMap;
    private readonly List<csvCommon.Common> _dataList;
    
    public TbCommon(JSONNode _json)
    {
        _dataMap = new Dictionary<int, csvCommon.Common>();
        _dataList = new List<csvCommon.Common>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = csvCommon.Common.DeserializeCommon(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public Dictionary<int, csvCommon.Common> DataMap => _dataMap;
    public List<csvCommon.Common> DataList => _dataList;

    public csvCommon.Common GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public csvCommon.Common Get(int key) => _dataMap[key];
    public csvCommon.Common this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
}

}