
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.csvFishingStage
{

public sealed class TbFishingStage
{
    private readonly Dictionary<int, csvFishingStage.FishingStage> _dataMap;
    private readonly List<csvFishingStage.FishingStage> _dataList;
    
    public TbFishingStage(JSONNode _json)
    {
        _dataMap = new Dictionary<int, csvFishingStage.FishingStage>();
        _dataList = new List<csvFishingStage.FishingStage>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = csvFishingStage.FishingStage.DeserializeFishingStage(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public Dictionary<int, csvFishingStage.FishingStage> DataMap => _dataMap;
    public List<csvFishingStage.FishingStage> DataList => _dataList;

    public csvFishingStage.FishingStage GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public csvFishingStage.FishingStage Get(int key) => _dataMap[key];
    public csvFishingStage.FishingStage this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
}

}