
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.csvDelivery
{

public sealed class Delivery :  Bright.Config.BeanBase 
{
    public Delivery(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["delivery_name"].IsString) { throw new SerializationException(); }  DeliveryName = _json["delivery_name"]; }
        { if(!_json["delivery_name_cn"].IsString) { throw new SerializationException(); }  DeliveryNameCn = _json["delivery_name_cn"]; }
        { if(!_json["delivery_type"].IsNumber) { throw new SerializationException(); }  DeliveryType = _json["delivery_type"]; }
        { if(!_json["delivery_content"].IsString) { throw new SerializationException(); }  DeliveryContent = _json["delivery_content"]; }
        { if(!_json["delivery_weight"].IsNumber) { throw new SerializationException(); }  DeliveryWeight = _json["delivery_weight"]; }
    }

    public Delivery(int id, string delivery_name, string delivery_name_cn, int delivery_type, string delivery_content, int delivery_weight ) 
    {
        this.Id = id;
        this.DeliveryName = delivery_name;
        this.DeliveryNameCn = delivery_name_cn;
        this.DeliveryType = delivery_type;
        this.DeliveryContent = delivery_content;
        this.DeliveryWeight = delivery_weight;
    }

    public static Delivery DeserializeDelivery(JSONNode _json)
    {
        return new csvDelivery.Delivery(_json);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 空投名称（英文）
    /// </summary>
    public string DeliveryName { get; private set; }
    /// <summary>
    /// 名称注释（中文）
    /// </summary>
    public string DeliveryNameCn { get; private set; }
    /// <summary>
    /// 效果类型<br/>1= A|B|C，抽取随机鱼pack<br/>2= 获取A道具<br/>3= 传送到随机一名其他玩家的收获区域，获取A秒的B加速倍率
    /// </summary>
    public int DeliveryType { get; private set; }
    /// <summary>
    /// 类型配置
    /// </summary>
    public string DeliveryContent { get; private set; }
    /// <summary>
    /// 权重
    /// </summary>
    public int DeliveryWeight { get; private set; }

    public const int __ID__ = 567726952;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "DeliveryName:" + DeliveryName + ","
        + "DeliveryNameCn:" + DeliveryNameCn + ","
        + "DeliveryType:" + DeliveryType + ","
        + "DeliveryContent:" + DeliveryContent + ","
        + "DeliveryWeight:" + DeliveryWeight + ","
        + "}";
    }
    }
}
