
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.csvDelivery
{

public sealed class TbDelivery
{
    private readonly Dictionary<int, csvDelivery.Delivery> _dataMap;
    private readonly List<csvDelivery.Delivery> _dataList;
    
    public TbDelivery(JSONNode _json)
    {
        _dataMap = new Dictionary<int, csvDelivery.Delivery>();
        _dataList = new List<csvDelivery.Delivery>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = csvDelivery.Delivery.DeserializeDelivery(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public Dictionary<int, csvDelivery.Delivery> DataMap => _dataMap;
    public List<csvDelivery.Delivery> DataList => _dataList;

    public csvDelivery.Delivery GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public csvDelivery.Delivery Get(int key) => _dataMap[key];
    public csvDelivery.Delivery this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
}

}